### ISSUE TITLE
Connecting to a message server

### ISSUE THREAD

**Issue by oliver-hermann** [nunomaia/NwRfcNet#39]
Hello,

thank you for your work on this package, I really appreciate it!

I was wondering if you support connecting to a message server since the constructor does not accept the parameters MSHOST, R3NAME/SystemId and GROUP.
Am I missing something here?
I'm not an SAP dev, just trying to interface with it, so excuse me if I'm on the wrong track..

If you do not support it, do you plan on adding support?

Cheers

**Comment by nunomaia** [comment]
Hi,

I didn’t exposed load balancing connection properties because I don’t have an environment to test t. If you have the possibility make a pull request off that change.

Each connection property is exposed in class RfcConnectionBuilder 

For example language is defined using 
```
[RfcConnectionPropertyAttribute("lang")]
public string Language { get ; set; }
```

Add those 3 additional  properties

**Comment by oliver-hermann** [comment]
Thanks for merging the PR!
When do you plan to release the next version to nuget?

Cheers

**Comment by nunomaia** [comment]
an updated NuGet was released today

**Comment by oliver-hermann** [comment]
All right, thanks a bunch!
